# Generated by Django 3.2.4 on 2021-07-21 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='image_url',
        ),
        migrations.AddField(
            model_name='pet',
            name='image',
            field=models.ImageField(default='static/default_pics/default.jpg', upload_to='pet_photos/'),
        ),
    ]
