# Generated by Django 3.2.4 on 2021-07-22 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0007_alter_pet_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=models.ImageField(default='default_pics/default.jpg', upload_to='pet_photos/'),
        ),
    ]
